;;; chroma-palette.el --- Finite Chroma palettes  -*- lexical-binding: t; -*-

;; Copyright (C) 2026 Chroma Theme contributors

;; Author: Chroma Theme contributors
;; Keywords: faces
;; Package-Requires: ((emacs "28.1"))

;; This file is part of Chroma Theme.

;; Chroma Theme is free software: you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.

;; Chroma Theme is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.

;;; Commentary:

;; This library contains only author-defined, finite palette data.  It does
;; not generate or adjust colors at run time.  Dark and light are separate,
;; independently verified data sets; the outer levels leave room for reduced-
;; color display classes.  Chromatic leaves target the canonical OKLCH angle
;; of their hue.  Source-relative tones retain their OKLab lightness and
;; chroma; contrast-critical status and indicator tones retain their source
;; WCAG relative luminance and use the closest in-gamut lightness and chroma.

;;; Code:

(defconst chroma-supported-hues
  '(blue azure cyan green chartreuse yellow orange red magenta purple)
  "Hues available as primary and secondary colors.")

(defconst chroma-hue-angles
  '((blue . 270.0)
    (azure . 240.0)
    (cyan . 200.0)
    (green . 150.0)
    (chartreuse . 120.0)
    (yellow . 90.0)
    (orange . 60.0)
    (red . 20.0)
    (magenta . 330.0)
    (purple . 300.0))
  "Canonical OKLCH hue angle for every supported chromatic palette.")

(defconst chroma-supported-variants '(dark light)
  "Palette variants available in Chroma.")

(defconst chroma-primary-secondary-pairs
  '((blue . yellow)
    (azure . orange)
    (cyan . red)
    (green . magenta)
    (chartreuse . purple)
    (yellow . blue)
    (orange . azure)
    (red . cyan)
    (magenta . green)
    (purple . chartreuse))
  "Symmetric automatic complementary hue for each primary color.")

(defconst chroma-palette-required-neutral-tokens
  '(bg-main bg-subtle bg-highlight bg-selection
    bg-mode-line bg-panel bg-ui bg-ui-inactive
    bg-fixed-dark
    fg-main fg-secondary fg-dim fg-muted fg-faint fg-on-bright
    fg-fixed-light fg-fixed-light-gray
    fg-fixed-gray fg-fill-column
    border border-subtle border-leading border-trailing window-divider
    scrollbar)
  "Neutral tokens required by the semantic color layer.")

(defconst chroma-palette-required-hue-tokens
  '(muted selection standalone-selection refinement paren-match pulse
    diff-added diff-removed diff-refine-added diff-refine-removed
    magit-base magit-removed-highlight magit-added-highlight
    magit-base-highlight alert
    ansi-low ansi-low-bright ansi-mid ansi-mid-bright
    ansi-upper ansi-upper-bright ansi-high ansi-vivid
    base emphasis vivid
    status-error status-warning status-success
    strong polarity polarity-strong steady
    dark-only dark-only-emphasis fixed-dark
    changed-indicator fine-a fine-ancestor fine-b fine-c
    current-a current-ancestor current-b current-c
    search-group-1-background search-group-1-foreground
    search-group-2-background search-group-2-foreground
    indicator-removed indicator-added whitespace-big-foreground
    selected-link)
  "Tokens required for every hue in a Chroma palette.")

(defconst chroma-palettes
  '((dark .
     ((true-color .
       ((neutral .
         ((bg-main . "#000000")
          (bg-subtle . "#191c23")
          (bg-highlight . "#242936")
          (bg-selection . "#30394b")
          (bg-mode-line . "#aeb6c5")
          (bg-panel . "#464d5a")
          (bg-ui . "#c4c9d4")
          (bg-ui-inactive . "#9aa3b2")
          (bg-fixed-dark . "#111318")
          (fg-main . "#e6e9ef")
          (fg-secondary . "#c4c9d4")
          (fg-dim . "#9aa3b2")
          (fg-muted . "#7f899a")
          (fg-faint . "#687184")
          (fg-on-bright . "#111318")
          (fg-fixed-light . "#ffffff")
          (fg-fixed-light-gray . "#d3d3d3")
          (fg-fixed-gray . "#a9a9a9")
          (fg-fill-column . "#b3b3b3")
          (border . "#566075")
          (border-subtle . "#343b49")
          (border-leading . "#c4c9d4")
          (border-trailing . "#566075")
          (window-divider . "#999999")
          (scrollbar . "#a8a8a8")))
        (blue .
         ((muted . "#283357")
          (selection . "#2300c5")
          (standalone-selection . "#5d6a8f")
          (refinement . "#4e5f95")
          (paren-match . "#748ad1")
          (pulse . "#839ef9")
          (diff-added . "#3d4971")
          (diff-removed . "#343d58")
          (diff-refine-added . "#6181ff")
          (diff-refine-removed . "#3b51bd")
          (magit-base . "#424f7a")
          (magit-removed-highlight . "#35426c")
          (magit-added-highlight . "#44548e")
          (magit-base-highlight . "#4e5f95")
          (alert . "#5977ff")
          (ansi-low . "#3145b9")
          (ansi-low-bright . "#374bca")
          (ansi-mid . "#4660f3")
          (ansi-mid-bright . "#5573ff")
          (ansi-upper . "#829eff")
          (ansi-upper-bright . "#9bb4ff")
          (ansi-high . "#b6c9ff")
          (ansi-vivid . "#d6e0ff")
          (base . "#849ff7")
          (emphasis . "#abc0ff")
          (vivid . "#e8eeff")
          (status-error . "#d0dcff")
          (status-warning . "#9ab2ff")
          (status-success . "#e1e9ff")
          (strong . "#e8eeff")
          (polarity . "#e1e9ff")
          (polarity-strong . "#f9fbff")
          (steady . "#607adb")
          (dark-only . "#c7d5ff")
          (dark-only-emphasis . "#ebf0ff")
          (fixed-dark . "#394fc2")
          (changed-indicator . "#92acff")
          (fine-a . "#3b51bd")
          (fine-ancestor . "#6a7ec0")
          (fine-b . "#6181ff")
          (fine-c . "#809dfe")
          (current-a . "#343d58")
          (current-ancestor . "#2d385b")
          (current-b . "#3d4971")
          (current-c . "#6a7fc3")
          (search-group-1-background . "#8aa6ff")
          (search-group-1-foreground . "#2f4296")
          (search-group-2-background . "#627ff0")
          (search-group-2-foreground . "#2f4296")
          (indicator-removed . "#3447aa")
          (indicator-added . "#5570d7")
          (whitespace-big-foreground . "#4258b5")
          (selected-link . "#e6edff")))
        (azure .
         ((muted . "#203c4f")
          (selection . "#00486d")
          (standalone-selection . "#4a708b")
          (refinement . "#2a6890")
          (paren-match . "#4696ca")
          (pulse . "#41adf0")
          (diff-added . "#24506c")
          (diff-removed . "#244155")
          (diff-refine-added . "#0296dd")
          (diff-refine-removed . "#006596")
          (magit-base . "#285776")
          (magit-removed-highlight . "#174967")
          (magit-added-highlight . "#145e88")
          (magit-base-highlight . "#2a6890")
          (alert . "#018fd2")
          (ansi-low . "#015b88")
          (ansi-low-bright . "#006494")
          (ansi-mid . "#017cb7")
          (ansi-mid-bright . "#008cce")
          (ansi-upper . "#0eafff")
          (ansi-upper-bright . "#64c1ff")
          (ansi-high . "#95d3ff")
          (ansi-vivid . "#c5e6ff")
          (base . "#68c3ff")
          (emphasis . "#9fd7ff")
          (vivid . "#dff1ff")
          (status-error . "#bae2ff")
          (status-warning . "#58beff")
          (status-success . "#d4edff")
          (strong . "#dff1ff")
          (polarity . "#d6edff")
          (polarity-strong . "#fffbf7")
          (steady . "#018dd0")
          (dark-only . "#b1deff")
          (dark-only-emphasis . "#e4f3ff")
          (fixed-dark . "#016596")
          (changed-indicator . "#46b9ff")
          (fine-a . "#006596")
          (fine-ancestor . "#3f89b9")
          (fine-b . "#0296dd")
          (fine-c . "#33aef5")
          (current-a . "#244155")
          (current-ancestor . "#153e57")
          (current-b . "#24506c")
          (current-c . "#3c8bbd")
          (search-group-1-background . "#47b9ff")
          (search-group-1-foreground . "#01517a")
          (search-group-2-background . "#0095da")
          (search-group-2-foreground . "#01517a")
          (indicator-removed . "#015a87")
          (indicator-added . "#0183c1")
          (whitespace-big-foreground . "#00699c")
          (selected-link . "#dbefff")))
        (cyan .
         ((muted . "#1c4244")
          (selection . "#004d51")
          (standalone-selection . "#3c7679")
          (refinement . "#007075")
          (paren-match . "#00a2a9")
          (pulse . "#00bac2")
          (diff-added . "#06565a")
          (diff-removed . "#174648")
          (diff-refine-added . "#00a1a8")
          (diff-refine-removed . "#006c71")
          (magit-base . "#0a5d61")
          (magit-removed-highlight . "#004f52")
          (magit-added-highlight . "#016569")
          (magit-base-highlight . "#007075")
          (alert . "#03999f")
          (ansi-low . "#006266")
          (ansi-low-bright . "#006b70")
          (ansi-mid . "#00858b")
          (ansi-mid-bright . "#02959b")
          (ansi-upper . "#03bbc3")
          (ansi-upper-bright . "#03d0d8")
          (ansi-high . "#04e6ef")
          (ansi-vivid . "#79f8ff")
          (base . "#56d8df")
          (emphasis . "#8beaef")
          (vivid . "#befcff")
          (status-error . "#05f4fe")
          (status-warning . "#03c8d0")
          (status-success . "#93faff")
          (strong . "#abfbff")
          (polarity . "#8af9ff")
          (polarity-strong . "#edffff")
          (steady . "#018f95")
          (dark-only . "#00edf6")
          (dark-only-emphasis . "#b6fcff")
          (fixed-dark . "#01666b")
          (changed-indicator . "#03c2ca")
          (fine-a . "#006c71")
          (fine-ancestor . "#00949a")
          (fine-b . "#00a1a8")
          (fine-c . "#00bac2")
          (current-a . "#174648")
          (current-ancestor . "#004346")
          (current-b . "#06565a")
          (current-c . "#02959b")
          (search-group-1-background . "#00bcc4")
          (search-group-1-foreground . "#015256")
          (search-group-2-background . "#02979d")
          (search-group-2-foreground . "#015256")
          (indicator-removed . "#006367")
          (indicator-added . "#028d93")
          (whitespace-big-foreground . "#017176")
          (selected-link . "#d3fdff")))
        (green .
         ((muted . "#27422d")
          (selection . "#005222")
          (standalone-selection . "#527559")
          (refinement . "#387046")
          (paren-match . "#58a169")
          (pulse . "#5cbb74")
          (diff-added . "#2e5637")
          (diff-removed . "#2a4530")
          (diff-refine-added . "#05aa4e")
          (diff-refine-removed . "#037232")
          (magit-base . "#335d3c")
          (magit-removed-highlight . "#234f2f")
          (magit-added-highlight . "#28673a")
          (magit-base-highlight . "#397046")
          (alert . "#00a149")
          (ansi-low . "#01672c")
          (ansi-low-bright . "#017131")
          (ansi-mid . "#008c3f")
          (ansi-mid-bright . "#009e48")
          (ansi-upper . "#02c55b")
          (ansi-upper-bright . "#00dc67")
          (ansi-high . "#2ff077")
          (ansi-vivid . "#8cffa7")
          (base . "#8cd49b")
          (emphasis . "#b4e6bd")
          (vivid . "#c7ffd1")
          (status-error . "#70f795")
          (status-warning . "#41cd6d")
          (status-success . "#9affb0")
          (strong . "#b5ffc4")
          (polarity . "#99ffb0")
          (polarity-strong . "#f1fff3")
          (steady . "#219449")
          (dark-only . "#82ed9c")
          (dark-only-emphasis . "#c0ffcc")
          (fixed-dark . "#016b2e")
          (changed-indicator . "#51c571")
          (fine-a . "#037232")
          (fine-ancestor . "#4f9360")
          (fine-b . "#05aa4e")
          (fine-c . "#54bc70")
          (current-a . "#2a4530")
          (current-ancestor . "#1e4328")
          (current-b . "#2e5637")
          (current-c . "#4f9560")
          (search-group-1-background . "#3fc268")
          (search-group-1-foreground . "#015624")
          (search-group-2-background . "#029d47")
          (search-group-2-foreground . "#015624")
          (indicator-removed . "#02662c")
          (indicator-added . "#009343")
          (whitespace-big-foreground . "#007835")
          (selected-link . "#e4ffe8")))
        (chartreuse .
         ((muted . "#2f380e")
          (selection . "#3d4a00")
          (standalone-selection . "#667148")
          (refinement . "#5c6929")
          (paren-match . "#869846")
          (pulse . "#99b043")
          (diff-added . "#475124")
          (diff-removed . "#3a4224")
          (diff-refine-added . "#839a00")
          (diff-refine-removed . "#566701")
          (magit-base . "#4d5829")
          (magit-removed-highlight . "#3f4a19")
          (magit-added-highlight . "#516016")
          (magit-base-highlight . "#5c6929")
          (alert . "#7c9200")
          (ansi-low . "#4e5d00")
          (ansi-low-bright . "#566600")
          (ansi-mid . "#6b7e00")
          (ansi-mid-bright . "#798f00")
          (ansi-upper . "#98b31f")
          (ansi-upper-bright . "#adc363")
          (ansi-high . "#c3d493")
          (ansi-vivid . "#dde7c4")
          (base . "#a3b859")
          (emphasis . "#bfd187")
          (vivid . "#ecf1dd")
          (status-error . "#d7e1ba")
          (status-warning . "#a8be5f")
          (status-success . "#e5ecd3")
          (strong . "#ecf2df")
          (polarity . "#e7eed5")
          (polarity-strong . "#fcfbff")
          (steady . "#7b9100")
          (dark-only . "#d2dfaf")
          (dark-only-emphasis . "#eef3e2")
          (fixed-dark . "#5a6a00")
          (changed-indicator . "#a2b951")
          (fine-a . "#566701")
          (fine-ancestor . "#7a8b40")
          (fine-b . "#839a00")
          (fine-c . "#98b037")
          (current-a . "#3a4224")
          (current-ancestor . "#363f16")
          (current-b . "#475124")
          (current-c . "#7b8c3b")
          (search-group-1-background . "#a2bb47")
          (search-group-1-foreground . "#475500")
          (search-group-2-background . "#829900")
          (search-group-2-foreground . "#475500")
          (indicator-removed . "#485600")
          (indicator-added . "#6b7f02")
          (whitespace-big-foreground . "#596a00")
          (selected-link . "#e3ebce")))
        (yellow .
         ((muted . "#4a3f22")
          (selection . "#534100")
          (standalone-selection . "#796a41")
          (refinement . "#765f1a")
          (paren-match . "#a88a32")
          (pulse . "#c59f23")
          (diff-added . "#5a4a1a")
          (diff-removed . "#483d1d")
          (diff-refine-added . "#ac8800")
          (diff-refine-removed . "#745b00")
          (magit-base . "#61501d")
          (magit-removed-highlight . "#53420a")
          (magit-added-highlight . "#6d5500")
          (magit-base-highlight . "#765f1a")
          (alert . "#a48100")
          (ansi-low . "#695200")
          (ansi-low-bright . "#735a00")
          (ansi-mid . "#8f7101")
          (ansi-mid-bright . "#a07f02")
          (ansi-upper . "#c89f01")
          (ansi-upper-bright . "#dfb100")
          (ansi-high . "#f6c400")
          (ansi-vivid . "#ffde84")
          (base . "#e6c463")
          (emphasis . "#f4d88d")
          (vivid . "#ffeebf")
          (status-error . "#ffd96f")
          (status-warning . "#dcaf02")
          (status-success . "#ffe7a8")
          (strong . "#ffedbc")
          (polarity . "#ffe7a7")
          (polarity-strong . "#fffbee")
          (steady . "#9e7d01")
          (dark-only . "#fcd151")
          (dark-only-emphasis . "#ffefc4")
          (fixed-dark . "#715901")
          (changed-indicator . "#d6aa01")
          (fine-a . "#745b00")
          (fine-ancestor . "#9a7e2d")
          (fine-b . "#ac8800")
          (fine-c . "#c79e01")
          (current-a . "#483d1d")
          (current-ancestor . "#46380b")
          (current-b . "#5a4a1a")
          (current-c . "#9c7f29")
          (search-group-1-background . "#cfa400")
          (search-group-1-foreground . "#5c4700")
          (search-group-2-background . "#a68300")
          (search-group-2-foreground . "#5c4700")
          (indicator-removed . "#725900")
          (indicator-added . "#a17f00")
          (whitespace-big-foreground . "#795f00")
          (selected-link . "#ffefc3")))
        (orange .
         ((muted . "#4b331f")
          (selection . "#653500")
          (standalone-selection . "#856347")
          (refinement . "#875528")
          (paren-match . "#bf7d43")
          (pulse . "#e18d3f")
          (diff-added . "#664223")
          (diff-removed . "#513822")
          (diff-refine-added . "#ce7300")
          (diff-refine-removed . "#8b4c01")
          (magit-base . "#6f4826")
          (magit-removed-highlight . "#603a17")
          (magit-added-highlight . "#7f4914")
          (magit-base-highlight . "#875528")
          (alert . "#c46d00")
          (ansi-low . "#7f4400")
          (ansi-low-bright . "#8a4b00")
          (ansi-mid . "#ab5e00")
          (ansi-mid-bright . "#c06a00")
          (ansi-upper . "#ef8600")
          (ansi-upper-bright . "#ff9c3e")
          (ansi-high . "#ffba81")
          (ansi-vivid . "#ffd9bc")
          (base . "#f5a45e")
          (emphasis . "#ffc18e")
          (vivid . "#ffeada")
          (status-error . "#ffd5b4")
          (status-warning . "#ff9e43")
          (status-success . "#ffe4d0")
          (strong . "#ffeada")
          (polarity . "#ffe4d0")
          (polarity-strong . "#fffbf7")
          (steady . "#c16c03")
          (dark-only . "#ffcca4")
          (dark-only-emphasis . "#ffeddf")
          (fixed-dark . "#8c4c00")
          (changed-indicator . "#fb9735")
          (fine-a . "#8b4c01")
          (fine-ancestor . "#af723c")
          (fine-b . "#ce7300")
          (fine-c . "#e58a33")
          (current-a . "#513822")
          (current-ancestor . "#523114")
          (current-b . "#664223")
          (current-c . "#b2723a")
          (search-group-1-background . "#fa901b")
          (search-group-1-foreground . "#713d01")
          (search-group-2-background . "#cb7202")
          (search-group-2-foreground . "#713d01")
          (indicator-removed . "#804500")
          (indicator-added . "#b86601")
          (whitespace-big-foreground . "#914f00")
          (selected-link . "#ffe7d5")))
        (red .
         ((muted . "#4b2727")
          (selection . "#82001e")
          (standalone-selection . "#8b5d5d")
          (refinement . "#8e4c4d")
          (paren-match . "#c97071")
          (pulse . "#ed7d7f")
          (diff-added . "#6c3c3c")
          (diff-removed . "#553333")
          (diff-refine-added . "#f04857")
          (diff-refine-removed . "#aa2033")
          (magit-base . "#754141")
          (magit-removed-highlight . "#663334")
          (magit-added-highlight . "#864042")
          (magit-base-highlight . "#8e4c4d")
          (alert . "#ee314b")
          (ansi-low . "#a10027")
          (ansi-low-bright . "#b0002c")
          (ansi-mid . "#d80e3a")
          (ansi-mid-bright . "#ea2d48")
          (ansi-upper . "#ff7177")
          (ansi-upper-bright . "#ff9495")
          (ansi-high . "#ffb4b3")
          (ansi-vivid . "#ffd6d5")
          (base . "#f07175")
          (emphasis . "#ff9b9b")
          (vivid . "#ffe9e8")
          (status-error . "#ffd2d1")
          (status-warning . "#ff9898")
          (status-success . "#ffe3e2")
          (strong . "#ffe9e8")
          (polarity . "#ffe3e2")
          (polarity-strong . "#fffafa")
          (steady . "#d25b60")
          (dark-only . "#ffc9c8")
          (dark-only-emphasis . "#ffeceb")
          (fixed-dark . "#b21f34")
          (changed-indicator . "#ff8f90")
          (fine-a . "#aa2033")
          (fine-ancestor . "#b86768")
          (fine-b . "#f04857")
          (fine-c . "#f1797c")
          (current-a . "#553333")
          (current-ancestor . "#562c2c")
          (current-b . "#6c3c3c")
          (current-c . "#bb6768")
          (search-group-1-background . "#ff8688")
          (search-group-1-foreground . "#8b222d")
          (search-group-2-background . "#e35b62")
          (search-group-2-foreground . "#8b222d")
          (indicator-removed . "#98192c")
          (indicator-added . "#c64850")
          (whitespace-big-foreground . "#a5323c")
          (selected-link . "#ffdddc")))
        (magenta .
         ((muted . "#462b43")
          (selection . "#71006e")
          (standalone-selection . "#7f5f7c")
          (refinement . "#7f4e7a")
          (paren-match . "#b474ae")
          (pulse . "#d382cc")
          (diff-added . "#613d5d")
          (diff-removed . "#4d344a")
          (diff-refine-added . "#ce55c7")
          (diff-refine-removed . "#902d8b")
          (magit-base . "#684365")
          (magit-removed-highlight . "#5a3556")
          (magit-added-highlight . "#764372")
          (magit-base-highlight . "#7f4e7a")
          (alert . "#ca44c3")
          (ansi-low . "#8c0888")
          (ansi-low-bright . "#961a91")
          (ansi-mid . "#b62eb0")
          (ansi-mid-bright . "#c740c0")
          (ansi-upper . "#ed66e5")
          (ansi-upper-bright . "#ff7ef6")
          (ansi-high . "#ffa7f7")
          (ansi-vivid . "#ffd0fa")
          (base . "#d88cd1")
          (emphasis . "#eeb0e7")
          (vivid . "#ffe5fc")
          (status-error . "#fecef9")
          (status-warning . "#fb8df2")
          (status-success . "#ffe0fb")
          (strong . "#ffe7fc")
          (polarity . "#ffe0fb")
          (polarity-strong . "#fffafe")
          (steady . "#b862b1")
          (dark-only . "#ffc4f9")
          (dark-only-emphasis . "#ffeafc")
          (fixed-dark . "#972f92")
          (changed-indicator . "#ee8de6")
          (fine-a . "#902d8b")
          (fine-ancestor . "#a56a9f")
          (fine-b . "#ce55c7")
          (fine-c . "#d57fce")
          (current-a . "#4d344a")
          (current-ancestor . "#4d2d4a")
          (current-b . "#613d5d")
          (current-c . "#a76aa2")
          (search-group-1-background . "#ec85e4")
          (search-group-1-foreground . "#772a72")
          (search-group-2-background . "#c663bf")
          (search-group-2-foreground . "#772a72")
          (indicator-removed . "#842a7f")
          (indicator-added . "#af53a9")
          (whitespace-big-foreground . "#8d3988")
          (selected-link . "#ffd7fa")))
        (purple .
         ((muted . "#382b4e")
          (selection . "#58009c")
          (standalone-selection . "#706389")
          (refinement . "#6a568e")
          (paren-match . "#997ec7")
          (pulse . "#b18eec")
          (diff-added . "#51436b")
          (diff-removed . "#423854")
          (diff-refine-added . "#a368f4")
          (diff-refine-removed . "#6f3eaf")
          (magit-base . "#584973")
          (magit-removed-highlight . "#4a3b65")
          (magit-added-highlight . "#614a86")
          (magit-base-highlight . "#6a568e")
          (alert . "#9d5bf4")
          (ansi-low . "#6928b0")
          (ansi-low-bright . "#7233ba")
          (ansi-mid . "#8b46df")
          (ansi-mid-bright . "#9a57f0")
          (ansi-upper . "#b58afb")
          (ansi-upper-bright . "#c4a5fc")
          (ansi-high . "#d3befc")
          (ansi-vivid . "#e6dbfd")
          (base . "#b99aef")
          (emphasis . "#d1b9ff")
          (vivid . "#f1eafe")
          (status-error . "#e3d7fd")
          (status-warning . "#c5a6fd")
          (status-success . "#ede5fe")
          (strong . "#f1ebfe")
          (polarity . "#ede5fe")
          (polarity-strong . "#fcfbff")
          (steady . "#946dd1")
          (dark-only . "#decffd")
          (dark-only-emphasis . "#f3edfe")
          (fixed-dark . "#733fb7")
          (changed-indicator . "#c09ffc")
          (fine-a . "#6f3eaf")
          (fine-ancestor . "#8b73b6")
          (fine-b . "#a368f4")
          (fine-c . "#b28cf1")
          (current-a . "#423854")
          (current-ancestor . "#3f3255")
          (current-b . "#51436b")
          (current-c . "#8d73ba")
          (search-group-1-background . "#bc97fb")
          (search-group-1-foreground . "#5b368e")
          (search-group-2-background . "#9e70e4")
          (search-group-2-foreground . "#5b368e")
          (indicator-removed . "#62359c")
          (indicator-added . "#885ec7")
          (whitespace-big-foreground . "#6f48a8")
          (selected-link . "#eae1fe")))))))
    (light .
     ((true-color .
       ((neutral .
         ((bg-main . "#ffffff")
          (bg-subtle . "#eef0f4")
          (bg-highlight . "#e2e6ed")
          (bg-selection . "#d4dbea")
          (bg-mode-line . "#c6ccd6")
          (bg-panel . "#e2e6ed")
          (bg-ui . "#d9dde5")
          (bg-ui-inactive . "#c6ccd6")
          (bg-fixed-dark . "#111318")
          (fg-main . "#20242c")
          (fg-secondary . "#3f4653")
          (fg-dim . "#515b6c")
          (fg-muted . "#667080")
          (fg-faint . "#808897")
          (fg-on-bright . "#20242c")
          (fg-fixed-light . "#ffffff")
          (fg-fixed-light-gray . "#d3d3d3")
          (fg-fixed-gray . "#d3d3d3")
          (fg-fill-column . "#808080")
          (border . "#8b95a5")
          (border-subtle . "#c6ccd6")
          (border-leading . "#c6ccd6")
          (border-trailing . "#667080")
          (window-divider . "#999999")
          (scrollbar . "#505050")))
        (blue .
         ((muted . "#dee5fb")
          (selection . "#cddaff")
          (standalone-selection . "#f0f4ff")
          (refinement . "#cfdbff")
          (paren-match . "#aec2ff")
          (pulse . "#f6f9ff")
          (diff-added . "#f6f9ff")
          (diff-removed . "#ecf3ff")
          (diff-refine-added . "#e3eaff")
          (diff-refine-removed . "#ccd9ff")
          (magit-base . "#f9fbff")
          (magit-removed-highlight . "#cbd5f0")
          (magit-added-highlight . "#d9e3ff")
          (magit-base-highlight . "#e2eaff")
          (alert . "#5977ff")
          (ansi-low . "#3145b9")
          (ansi-low-bright . "#374bca")
          (ansi-mid . "#4660f3")
          (ansi-mid-bright . "#5573ff")
          (ansi-upper . "#829eff")
          (ansi-upper-bright . "#9bb4ff")
          (ansi-high . "#b6c9ff")
          (ansi-vivid . "#d6e0ff")
          (base . "#435bbd")
          (emphasis . "#31449e")
          (vivid . "#3e55c8")
          (status-error . "#5672e7")
          (status-warning . "#85a1ff")
          (status-success . "#506be0")
          (strong . "#121b56")
          (polarity . "#6887ff")
          (polarity-strong . "#364aad")
          (steady . "#546dcd")
          (dark-only . "#20242c")
          (dark-only-emphasis . "#20242c")
          (fixed-dark . "#394fc2")
          (changed-indicator . "#7d9aff")
          (fine-a . "#bdceff")
          (fine-ancestor . "#8da7fd")
          (fine-b . "#dde6ff")
          (fine-c . "#f1f6ff")
          (current-a . "#dde6ff")
          (current-ancestor . "#d5dcef")
          (current-b . "#eef4ff")
          (current-c . "#f6f9ff")
          (search-group-1-background . "#6380f0")
          (search-group-1-foreground . "#cedbff")
          (search-group-2-background . "#384eb9")
          (search-group-2-foreground . "#cedbff")
          (indicator-removed . "#3447aa")
          (indicator-added . "#627ee7")
          (whitespace-big-foreground . "#4258b5")
          (selected-link . "#4760d4")))
        (azure .
         ((muted . "#d3e8f8")
          (selection . "#b8e1ff")
          (standalone-selection . "#ebf6ff")
          (refinement . "#bbe2ff")
          (paren-match . "#87ceff")
          (pulse . "#f3faff")
          (diff-added . "#f4faff")
          (diff-removed . "#e8f5fe")
          (diff-refine-added . "#d8eeff")
          (diff-refine-removed . "#b9e1fe")
          (magit-base . "#f7fcff")
          (magit-removed-highlight . "#bfdaed")
          (magit-added-highlight . "#c8e8ff")
          (magit-base-highlight . "#d6eeff")
          (alert . "#018fd2")
          (ansi-low . "#015b88")
          (ansi-low-bright . "#006494")
          (ansi-mid . "#017cb7")
          (ansi-mid-bright . "#008cce")
          (ansi-upper . "#0eafff")
          (ansi-upper-bright . "#64c1ff")
          (ansi-high . "#95d3ff")
          (ansi-vivid . "#c5e6ff")
          (base . "#006393")
          (emphasis . "#004e76")
          (vivid . "#006a9d")
          (status-error . "#0082bf")
          (status-warning . "#07afff")
          (status-success . "#017bb6")
          (strong . "#00273d")
          (polarity . "#029de6")
          (polarity-strong . "#005d8b")
          (steady . "#017fbb")
          (dark-only . "#20242c")
          (dark-only-emphasis . "#20242c")
          (fixed-dark . "#016596")
          (changed-indicator . "#03a8f5")
          (fine-a . "#a0d7fe")
          (fine-ancestor . "#56b6f4")
          (fine-b . "#cfeaff")
          (fine-c . "#edf7ff")
          (current-a . "#d1ebfe")
          (current-ancestor . "#cddfed")
          (current-b . "#eaf6ff")
          (current-c . "#f3faff")
          (search-group-1-background . "#0295db")
          (search-group-1-foreground . "#bce3ff")
          (search-group-2-background . "#006292")
          (search-group-2-foreground . "#bce3ff")
          (indicator-removed . "#015580")
          (indicator-added . "#018cce")
          (whitespace-big-foreground . "#00699c")
          (selected-link . "#0174ac")))
        (cyan .
         ((muted . "#d5eeef")
          (selection . "#73f1f8")
          (standalone-selection . "#d7fdff")
          (refinement . "#89f0f5")
          (paren-match . "#35dee6")
          (pulse . "#e8feff")
          (diff-added . "#eafeff")
          (diff-removed . "#e5f6f9")
          (diff-refine-added . "#abfbff")
          (diff-refine-removed . "#aee7ea")
          (magit-base . "#f0feff")
          (magit-removed-highlight . "#b9dee0")
          (magit-added-highlight . "#b6eff2")
          (magit-base-highlight . "#b6f8fb")
          (alert . "#03999f")
          (ansi-low . "#006266")
          (ansi-low-bright . "#006b70")
          (ansi-mid . "#00858b")
          (ansi-mid-bright . "#02959b")
          (ansi-upper . "#03bbc3")
          (ansi-upper-bright . "#03d0d8")
          (ansi-high . "#04e6ef")
          (ansi-vivid . "#79f8ff")
          (base . "#006c71")
          (emphasis . "#005256")
          (vivid . "#007176")
          (status-error . "#03888e")
          (status-warning . "#00b8bf")
          (status-success . "#028187")
          (strong . "#00282a")
          (polarity . "#00a0a7")
          (polarity-strong . "#025e62")
          (steady . "#018187")
          (dark-only . "#20242c")
          (dark-only-emphasis . "#20242c")
          (fixed-dark . "#01666b")
          (changed-indicator . "#03b0b7")
          (fine-a . "#8fdfe3")
          (fine-ancestor . "#00c3cb")
          (fine-b . "#96faff")
          (fine-c . "#dbfdff")
          (current-a . "#cbeff1")
          (current-ancestor . "#c8e2e3")
          (current-b . "#d5fdff")
          (current-c . "#e8feff")
          (search-group-1-background . "#02979d")
          (search-group-1-foreground . "#36f1fa")
          (search-group-2-background . "#026367")
          (search-group-2-foreground . "#36f1fa")
          (indicator-removed . "#005d61")
          (indicator-added . "#02969c")
          (whitespace-big-foreground . "#017176")
          (selected-link . "#027d82")))
        (green .
         ((muted . "#dcecdf")
          (selection . "#a4f0b3")
          (standalone-selection . "#ddffe2")
          (refinement . "#aeefba")
          (paren-match . "#83dd97")
          (pulse . "#ebffef")
          (diff-added . "#edfff0")
          (diff-removed . "#eaf6ec")
          (diff-refine-added . "#b7ffc6")
          (diff-refine-removed . "#c0e6c7")
          (magit-base . "#f2fff4")
          (magit-removed-highlight . "#c4ddc9")
          (magit-added-highlight . "#c9efcf")
          (magit-base-highlight . "#cbf7d3")
          (alert . "#00a149")
          (ansi-low . "#01672c")
          (ansi-low-bright . "#017131")
          (ansi-mid . "#008c3f")
          (ansi-mid-bright . "#009e48")
          (ansi-upper . "#02c55b")
          (ansi-upper-bright . "#00dc67")
          (ansi-high . "#2ff077")
          (ansi-vivid . "#8cffa7")
          (base . "#29663a")
          (emphasis . "#184f28")
          (vivid . "#007835")
          (status-error . "#018e40")
          (status-warning . "#2bbd5e")
          (status-success . "#00873d")
          (strong . "#002a0e")
          (polarity . "#02a74c")
          (polarity-strong . "#01622a")
          (steady . "#01863c")
          (dark-only . "#20242c")
          (dark-only-emphasis . "#20242c")
          (fixed-dark . "#016b2e")
          (changed-indicator . "#3db462")
          (fine-a . "#abdeb4")
          (fine-ancestor . "#6cc380")
          (fine-b . "#a5ffb8")
          (fine-c . "#e0ffe5")
          (current-a . "#d6eed9")
          (current-ancestor . "#d0e2d3")
          (current-b . "#dcffe1")
          (current-c . "#ebffef")
          (search-group-1-background . "#029e48")
          (search-group-1-foreground . "#8ef1a5")
          (search-group-2-background . "#01672c")
          (search-group-2-foreground . "#8ef1a5")
          (indicator-removed . "#006029")
          (indicator-added . "#139b49")
          (whitespace-big-foreground . "#007835")
          (selected-link . "#00843b")))
        (chartreuse .
         ((muted . "#dfe6ce")
          (selection . "#d1e690")
          (standalone-selection . "#ecffb3")
          (refinement . "#d4e69c")
          (paren-match . "#bad16c")
          (pulse . "#f4ffd6")
          (diff-added . "#f7fde7")
          (diff-removed . "#f1f5e7")
          (diff-refine-added . "#e0f69f")
          (diff-refine-removed . "#d6e1b6")
          (magit-base . "#f8ffe5")
          (magit-removed-highlight . "#d2dabe")
          (magit-added-highlight . "#dee9bf")
          (magit-base-highlight . "#e4f1c0")
          (alert . "#7c9200")
          (ansi-low . "#4e5d00")
          (ansi-low-bright . "#566600")
          (ansi-mid . "#6b7e00")
          (ansi-mid-bright . "#798f00")
          (ansi-upper . "#98b31f")
          (ansi-upper-bright . "#adc363")
          (ansi-high . "#c3d493")
          (ansi-vivid . "#dde7c4")
          (base . "#556500")
          (emphasis . "#414e00")
          (vivid . "#5b6c00")
          (status-error . "#6f8300")
          (status-warning . "#97b02c")
          (status-success . "#697d02")
          (strong . "#242c00")
          (polarity . "#8aa301")
          (polarity-strong . "#526100")
          (steady . "#6e8301")
          (dark-only . "#20242c")
          (dark-only-emphasis . "#20242c")
          (fixed-dark . "#5a6a00")
          (changed-indicator . "#90aa17")
          (fine-a . "#c8d89e")
          (fine-ancestor . "#a2b855")
          (fine-b . "#daf484")
          (fine-c . "#edffbc")
          (current-a . "#e3ebcf")
          (current-ancestor . "#dadfcb")
          (current-b . "#effad0")
          (current-c . "#f4ffd6")
          (search-group-1-background . "#829a00")
          (search-group-1-foreground . "#d8e3b9")
          (search-group-2-background . "#576700")
          (search-group-2-foreground . "#d8e3b9")
          (indicator-removed . "#475500")
          (indicator-added . "#778c00")
          (whitespace-big-foreground . "#596a00")
          (selected-link . "#637600")))
        (yellow .
         ((muted . "#f4e7c5")
          (selection . "#f8d880")
          (standalone-selection . "#fff4d6")
          (refinement . "#f6da8f")
          (paren-match . "#e6c157")
          (pulse . "#fef8e9")
          (diff-added . "#fff9eb")
          (diff-removed . "#f8f2e5")
          (diff-refine-added . "#ffe9ae")
          (diff-refine-removed . "#e9daaf")
          (magit-base . "#fffbf0")
          (magit-removed-highlight . "#e0d5b9")
          (magit-added-highlight . "#f2e3b8")
          (magit-base-highlight . "#fbe9b8")
          (alert . "#a48100")
          (ansi-low . "#695200")
          (ansi-low-bright . "#735a00")
          (ansi-mid . "#8f7101")
          (ansi-mid-bright . "#a07f02")
          (ansi-upper . "#c89f01")
          (ansi-upper-bright . "#dfb100")
          (ansi-high . "#f6c400")
          (ansi-vivid . "#ffde84")
          (base . "#735a00")
          (emphasis . "#5a4600")
          (vivid . "#7a6000")
          (status-error . "#977700")
          (status-warning . "#caa000")
          (status-success . "#8f7101")
          (strong . "#2d2100")
          (polarity . "#b08b00")
          (polarity-strong . "#685100")
          (steady . "#8e7000")
          (dark-only . "#20242c")
          (dark-only-emphasis . "#20242c")
          (fixed-dark . "#715901")
          (changed-indicator . "#c29a03")
          (fine-a . "#e3ce93")
          (fine-ancestor . "#cba83f")
          (fine-b . "#ffe49b")
          (fine-c . "#fef5dd")
          (current-a . "#f0e6cb")
          (current-ancestor . "#e3dbc8")
          (current-b . "#fff3d5")
          (current-c . "#fef8e9")
          (search-group-1-background . "#a78400")
          (search-group-1-foreground . "#ffd764")
          (search-group-2-background . "#6e5600")
          (search-group-2-foreground . "#ffd764")
          (indicator-removed . "#664f00")
          (indicator-added . "#a48202")
          (whitespace-big-foreground . "#795f00")
          (selected-link . "#856901")))
        (orange .
         ((muted . "#f6e1d1")
          (selection . "#ffd0ab")
          (standalone-selection . "#fff2e8")
          (refinement . "#fed3b1")
          (paren-match . "#feb273")
          (pulse . "#fff7f2")
          (diff-added . "#fff8f3")
          (diff-removed . "#fdf0e7")
          (diff-refine-added . "#ffe5d1")
          (diff-refine-removed . "#f8d3b5")
          (magit-base . "#fffaf6")
          (magit-removed-highlight . "#ead0bc")
          (magit-added-highlight . "#fedcc1")
          (magit-base-highlight . "#fee4d0")
          (alert . "#c46d00")
          (ansi-low . "#7f4400")
          (ansi-low-bright . "#8a4b00")
          (ansi-mid . "#ab5e00")
          (ansi-mid-bright . "#c06a00")
          (ansi-upper . "#ef8600")
          (ansi-upper-bright . "#ff9c3e")
          (ansi-high . "#ffba81")
          (ansi-vivid . "#ffd9bc")
          (base . "#894a00")
          (emphasis . "#6d3a00")
          (vivid . "#925001")
          (status-error . "#b86601")
          (status-warning . "#f68a01")
          (status-success . "#af6101")
          (strong . "#391b00")
          (polarity . "#d77800")
          (polarity-strong . "#814601")
          (steady . "#ae6102")
          (dark-only . "#20242c")
          (dark-only-emphasis . "#20242c")
          (fixed-dark . "#8c4c00")
          (changed-indicator . "#e9861b")
          (fine-a . "#f7c49b")
          (fine-ancestor . "#e69752")
          (fine-b . "#fee0c8")
          (fine-c . "#fff3ea")
          (current-a . "#fae1ce")
          (current-ancestor . "#ebd8ca")
          (current-b . "#fff1e7")
          (current-c . "#fff7f2")
          (search-group-1-background . "#cc7201")
          (search-group-1-foreground . "#ffd3b0")
          (search-group-2-background . "#874a02")
          (search-group-2-foreground . "#ffd3b0")
          (indicator-removed . "#7a4201")
          (indicator-added . "#c66e00")
          (whitespace-big-foreground . "#914f00")
          (selected-link . "#a05800")))
        (red .
         ((muted . "#f4dad9")
          (selection . "#ffcccb")
          (standalone-selection . "#fff1f0")
          (refinement . "#ffcfce")
          (paren-match . "#ffabaa")
          (pulse . "#fff7f6")
          (diff-added . "#fff7f7")
          (diff-removed . "#ffeeed")
          (diff-refine-added . "#ffe3e2")
          (diff-refine-removed . "#ffcccb")
          (magit-base . "#fff9f9")
          (magit-removed-highlight . "#eecccb")
          (magit-added-highlight . "#ffd9d8")
          (magit-base-highlight . "#ffe2e1")
          (alert . "#ee314b")
          (ansi-low . "#a10027")
          (ansi-low-bright . "#b0002c")
          (ansi-mid . "#d80e3a")
          (ansi-mid-bright . "#ea2d48")
          (ansi-upper . "#ff7177")
          (ansi-upper-bright . "#ff9495")
          (ansi-high . "#ffb4b3")
          (ansi-vivid . "#ffd6d5")
          (base . "#a9323c")
          (emphasis . "#88222c")
          (vivid . "#b32035")
          (status-error . "#d84752")
          (status-warning . "#ff7e82")
          (status-success . "#d0404c")
          (strong . "#4e000e")
          (polarity . "#f15f67")
          (polarity-strong . "#a02332")
          (steady . "#c24d53")
          (dark-only . "#20242c")
          (dark-only-emphasis . "#20242c")
          (fixed-dark . "#b21f34")
          (changed-indicator . "#f9767a")
          (fine-a . "#ffbcbb")
          (fine-ancestor . "#f2898a")
          (fine-b . "#ffdddc")
          (fine-c . "#fff2f1")
          (current-a . "#ffdddc")
          (current-ancestor . "#eed6d5")
          (current-b . "#fff0ef")
          (current-c . "#fff7f6")
          (search-group-1-background . "#e45b62")
          (search-group-1-foreground . "#ffd0cf")
          (search-group-2-background . "#aa2234")
          (search-group-2-foreground . "#ffd0cf")
          (indicator-removed . "#97192b")
          (indicator-added . "#d6575d")
          (whitespace-big-foreground . "#a5323c")
          (selected-link . "#be2d3e")))
        (magenta .
         ((muted . "#eedbec")
          (selection . "#ffc5f9")
          (standalone-selection . "#ffeffd")
          (refinement . "#ffc7f8")
          (paren-match . "#f4a5ed")
          (pulse . "#fff5fd")
          (diff-added . "#fff6fe")
          (diff-removed . "#faeef8")
          (diff-refine-added . "#ffdffa")
          (diff-refine-removed . "#f2cded")
          (magit-base . "#fff9fe")
          (magit-removed-highlight . "#e5cde1")
          (magit-added-highlight . "#fad6f6")
          (magit-base-highlight . "#ffdefa")
          (alert . "#ca44c3")
          (ansi-low . "#8c0888")
          (ansi-low-bright . "#961a91")
          (ansi-mid . "#b62eb0")
          (ansi-mid-bright . "#c740c0")
          (ansi-upper . "#ed66e5")
          (ansi-upper-bright . "#ff7ef6")
          (ansi-high . "#ffa7f7")
          (ansi-vivid . "#ffd0fa")
          (base . "#8d3988")
          (emphasis . "#70286c")
          (vivid . "#982f93")
          (status-error . "#bb51b4")
          (status-warning . "#ea7ee2")
          (status-success . "#b34aad")
          (strong . "#450042")
          (polarity . "#d268cb")
          (polarity-strong . "#892f84")
          (steady . "#a954a3")
          (dark-only . "#20242c")
          (dark-only-emphasis . "#20242c")
          (fixed-dark . "#972f92")
          (changed-indicator . "#dc7dd5")
          (fine-a . "#edbde8")
          (fine-ancestor . "#d98dd2")
          (fine-b . "#fed8fa")
          (fine-c . "#fff0fd")
          (current-a . "#f6def2")
          (current-ancestor . "#e7d6e5")
          (current-b . "#ffeefc")
          (current-c . "#fff5fd")
          (search-group-1-background . "#c763c0")
          (search-group-1-foreground . "#ffcbf9")
          (search-group-2-background . "#91308c")
          (search-group-2-foreground . "#ffcbf9")
          (indicator-removed . "#81277d")
          (indicator-added . "#bb5fb5")
          (whitespace-big-foreground . "#8d3988")
          (selected-link . "#a23a9c")))
        (purple .
         ((muted . "#e6def6")
          (selection . "#e1d2ff")
          (standalone-selection . "#f6f2ff")
          (refinement . "#e2d4ff")
          (paren-match . "#cfb6ff")
          (pulse . "#f9f8ff")
          (diff-added . "#faf8ff")
          (diff-removed . "#f3f0fe")
          (diff-refine-added . "#eee6fe")
          (diff-refine-removed . "#e0d3fc")
          (magit-base . "#fbfaff")
          (magit-removed-highlight . "#d9d0ec")
          (magit-added-highlight . "#e8ddfe")
          (magit-base-highlight . "#ede5fe")
          (alert . "#9d5bf4")
          (ansi-low . "#6928b0")
          (ansi-low-bright . "#7233ba")
          (ansi-mid . "#8b46df")
          (ansi-mid-bright . "#9a57f0")
          (ansi-upper . "#b58afb")
          (ansi-upper-bright . "#c4a5fc")
          (ansi-high . "#d3befc")
          (ansi-vivid . "#e6dbfd")
          (base . "#6b41a4")
          (emphasis . "#542f85")
          (vivid . "#7541b8")
          (status-error . "#9360da")
          (status-warning . "#ba92fc")
          (status-success . "#8c5ad3")
          (strong . "#350063")
          (polarity . "#a877f2")
          (polarity-strong . "#693ca3")
          (steady . "#875fc2")
          (dark-only . "#20242c")
          (dark-only-emphasis . "#20242c")
          (fixed-dark . "#733fb7")
          (changed-indicator . "#b48af8")
          (fine-a . "#d7c4fb")
          (fine-ancestor . "#b999f1")
          (fine-b . "#eae1fd")
          (fine-c . "#f6f4ff")
          (current-a . "#eae1fd")
          (current-ancestor . "#dfd8ec")
          (current-b . "#f4f2ff")
          (current-c . "#f9f8ff")
          (search-group-1-background . "#9f71e4")
          (search-group-1-foreground . "#e2d5fd")
          (search-group-2-background . "#6f3fae")
          (search-group-2-foreground . "#e2d5fd")
          (indicator-removed . "#63369d")
          (indicator-added . "#976cd8")
          (whitespace-big-foreground . "#6f48a8")
          (selected-link . "#7e4bc3"))))))))
  "Finite palettes indexed by variant and display class.")

(defun chroma-palette-get (&optional variant display-class)
  "Return palette data for VARIANT and DISPLAY-CLASS.

VARIANT defaults to `dark', and DISPLAY-CLASS defaults to
`true-color'.  Signal `user-error' when the requested palette does not
exist.  The returned value is constant data and must not be modified."
  (let* ((selected-variant (or variant 'dark))
         (selected-class (or display-class 'true-color))
         (variant-data (alist-get selected-variant chroma-palettes))
         (palette (and variant-data
                       (alist-get selected-class variant-data))))
    (unless variant-data
      (user-error "Chroma has no %S variant" selected-variant))
    (unless palette
      (user-error "Chroma has no %S display palette for %S"
                  selected-class selected-variant))
    palette))

(defun chroma-palette-color (hue token &optional variant display-class)
  "Return the color for HUE and TOKEN.

Look up HUE and TOKEN in the finite palette selected by VARIANT and
DISPLAY-CLASS.  Signal `user-error' for an unknown hue or token."
  (let* ((palette (chroma-palette-get variant display-class))
         (hue-data (alist-get hue palette))
         (color (and hue-data (alist-get token hue-data))))
    (unless hue-data
      (user-error "Chroma palette has no %S hue" hue))
    (unless color
      (user-error "Chroma %S palette has no %S token" hue token))
    color))

(provide 'chroma-palette)

;;; chroma-palette.el ends here
