;;; chroma-palette.el --- Finite Chroma palettes  -*- lexical-binding: t; -*-

;; Copyright (C) 2026 Chroma Theme contributors

;; Author: Chroma Theme contributors
;; Keywords: faces
;; Package-Requires: ((emacs "28.1"))

;; This file is part of Chroma Theme.

;; Chroma Theme is free software: you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.

;; Chroma Theme is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.

;;; Commentary:

;; This library contains only author-defined, finite palette data.  It does
;; not generate or adjust colors at run time.  Dark and light are separate,
;; independently verified data sets; the outer levels leave room for reduced-
;; color display classes.

;;; Code:

(defconst chroma-supported-hues
  '(blue cyan green yellow orange red magenta purple)
  "Hues available as primary and secondary colors.")

(defconst chroma-supported-variants '(dark light)
  "Palette variants available in Chroma.")

(defconst chroma-primary-secondary-pairs
  '((blue . purple)
    (cyan . orange)
    (green . magenta)
    (yellow . blue)
    (orange . cyan)
    (red . green)
    (magenta . green)
    (purple . cyan))
  "Author-defined automatic secondary color for each primary color.")

(defconst chroma-palette-required-neutral-tokens
  '(bg-main bg-subtle bg-highlight bg-selection
    bg-mode-line bg-panel bg-ui bg-ui-inactive
    bg-fixed-dark
    fg-main fg-secondary fg-dim fg-muted fg-faint fg-on-bright
    fg-fixed-light fg-fixed-light-gray
    fg-fixed-gray fg-fill-column
    border border-subtle border-leading border-trailing window-divider
    scrollbar)
  "Neutral tokens required by the semantic color layer.")

(defconst chroma-palette-required-hue-tokens
  '(muted selection standalone-selection refinement alert
    ansi-low ansi-low-bright ansi-mid ansi-mid-bright
    ansi-upper ansi-upper-bright ansi-high ansi-vivid
    base emphasis vivid
    status-error status-warning status-success
    strong polarity polarity-strong steady
    dark-only dark-only-emphasis fixed-dark
    changed-indicator fine-a fine-ancestor fine-b fine-c
    current-a current-ancestor current-b current-c
    search-group-1-background search-group-1-foreground
    search-group-2-background search-group-2-foreground
    indicator-removed indicator-added whitespace-big-foreground
    selected-link)
  "Tokens required for every hue in a Chroma palette.")

(defconst chroma-palettes
  '((dark .
     ((true-color .
       ((neutral .
         ((bg-main . "#111318")
          (bg-subtle . "#191c23")
          (bg-highlight . "#242936")
          (bg-selection . "#30394b")
          (bg-mode-line . "#aeb6c5")
          (bg-panel . "#464d5a")
          (bg-ui . "#c4c9d4")
          (bg-ui-inactive . "#9aa3b2")
          (bg-fixed-dark . "#111318")
          (fg-main . "#e6e9ef")
          (fg-secondary . "#c4c9d4")
          (fg-dim . "#9aa3b2")
          (fg-muted . "#7f899a")
          (fg-faint . "#687184")
          (fg-on-bright . "#111318")
          (fg-fixed-light . "#ffffff")
          (fg-fixed-light-gray . "#d3d3d3")
          (fg-fixed-gray . "#a9a9a9")
          (fg-fill-column . "#b3b3b3")
          (border . "#566075")
          (border-subtle . "#343b49")
          (border-leading . "#c4c9d4")
          (border-trailing . "#566075")
          (window-divider . "#999999")
          (scrollbar . "#a8a8a8")))
        (blue .
         ((muted . "#243457")
          (selection . "#043b90")
          (standalone-selection . "#416bb0")
          (refinement . "#2d6fdc")
          (alert . "#317fff")
          (ansi-low . "#004cb8")
          (ansi-low-bright . "#0053c9")
          (ansi-mid . "#0d69f2")
          (ansi-mid-bright . "#2a7bff")
          (ansi-upper . "#6da4ff")
          (ansi-upper-bright . "#8db8ff")
          (ansi-high . "#adccff")
          (ansi-vivid . "#d1e2ff")
          (base . "#7aa2f7")
          (emphasis . "#a9c1ff")
          (vivid . "#e5efff")
          (status-error . "#cadeff")
          (status-warning . "#89b6ff")
          (status-success . "#ddeaff")
          (strong . "#e5efff")
          (polarity . "#ddeaff")
          (polarity-strong . "#f9fbff")
          (steady . "#4a80db")
          (dark-only . "#bfd8ff")
          (dark-only-emphasis . "#e8f1ff")
          (fixed-dark . "#1256c1")
          (changed-indicator . "#80b0ff")
          (fine-a . "#0c52bd")
          (fine-ancestor . "#4984e5")
          (fine-b . "#4f91ff")
          (fine-c . "#6ea5ff")
          (current-a . "#053885")
          (current-ancestor . "#10387a")
          (current-b . "#1a4a99")
          (current-c . "#4883e4")
          (search-group-1-background . "#77abff")
          (search-group-1-foreground . "#164796")
          (search-group-2-background . "#4786ef")
          (search-group-2-foreground . "#164796")
          (indicator-removed . "#124ca9")
          (indicator-added . "#3b75d5")
          (whitespace-big-foreground . "#295eb5")
          (selected-link . "#e3eeff")))
        (cyan .
         ((muted . "#1d4148")
          (selection . "#004c50")
          (standalone-selection . "#017b80")
          (refinement . "#01858a")
          (alert . "#03999f")
          (ansi-low . "#006266")
          (ansi-low-bright . "#006b70")
          (ansi-mid . "#01858a")
          (ansi-mid-bright . "#01959c")
          (ansi-upper . "#04bbc3")
          (ansi-upper-bright . "#01d0d9")
          (ansi-high . "#04e6ef")
          (ansi-vivid . "#79f8ff")
          (base . "#58d6e8")
          (emphasis . "#8be9f2")
          (vivid . "#befcff")
          (status-error . "#00f5f6")
          (status-warning . "#00c9c9")
          (status-success . "#65ffff")
          (strong . "#99fffe")
          (polarity . "#64ffff")
          (polarity-strong . "#edffff")
          (steady . "#009090")
          (dark-only . "#00eeee")
          (dark-only-emphasis . "#a9fffe")
          (fixed-dark . "#006767")
          (changed-indicator . "#00c3c3")
          (fine-a . "#006363")
          (fine-ancestor . "#009595")
          (fine-b . "#00a4a4")
          (fine-c . "#00b7b8")
          (current-a . "#004444")
          (current-ancestor . "#004343")
          (current-b . "#005757")
          (current-c . "#009394")
          (search-group-1-background . "#00bdbe")
          (search-group-1-foreground . "#005353")
          (search-group-2-background . "#009898")
          (search-group-2-foreground . "#005353")
          (indicator-removed . "#006363")
          (indicator-added . "#008e8e")
          (whitespace-big-foreground . "#007272")
          (selected-link . "#cdfffe")))
        (green .
         ((muted . "#24422f")
          (selection . "#005211")
          (standalone-selection . "#387d3d")
          (refinement . "#008d24")
          (alert . "#00a22b")
          (ansi-low . "#006818")
          (ansi-low-bright . "#01721c")
          (ansi-mid . "#008d24")
          (ansi-mid-bright . "#019f2a")
          (ansi-upper . "#19c63c")
          (ansi-upper-bright . "#3cda52")
          (ansi-high . "#56ee66")
          (ansi-vivid . "#92ff98")
          (base . "#8bd49c")
          (emphasis . "#b3e6be")
          (vivid . "#caffca")
          (status-error . "#82f589")
          (status-warning . "#58cc61")
          (status-success . "#9fffa2")
          (strong . "#b9ffba")
          (polarity . "#9fffa2")
          (polarity-strong . "#f2fff1")
          (steady . "#36933f")
          (dark-only . "#8feb92")
          (dark-only-emphasis . "#c3ffc4")
          (fixed-dark . "#006c19")
          (changed-indicator . "#61c467")
          (fine-a . "#006718")
          (fine-ancestor . "#32983d")
          (fine-b . "#2fa93f")
          (fine-c . "#46bb51")
          (current-a . "#00470e")
          (current-ancestor . "#00460d")
          (current-b . "#005a14")
          (current-c . "#30973c")
          (search-group-1-background . "#54c05c")
          (search-group-1-foreground . "#005713")
          (search-group-2-background . "#2b9c3a")
          (search-group-2-foreground . "#005713")
          (indicator-removed . "#006718")
          (indicator-added . "#299136")
          (whitespace-big-foreground . "#107823")
          (selected-link . "#e5ffe5")))
        (yellow .
         ((muted . "#494022")
          (selection . "#4f4100")
          (standalone-selection . "#806a01")
          (refinement . "#8a7302")
          (alert . "#9e8401")
          (ansi-low . "#655401")
          (ansi-low-bright . "#6f5c00")
          (ansi-mid . "#8a7302")
          (ansi-mid-bright . "#9b8101")
          (ansi-upper . "#c2a202")
          (ansi-upper-bright . "#d8b501")
          (ansi-high . "#eec804")
          (ansi-vivid . "#ffe068")
          (base . "#e5c463")
          (emphasis . "#f2d98d")
          (vivid . "#ffefb2")
          (status-error . "#ffdb43")
          (status-warning . "#d4b200")
          (status-success . "#ffe994")
          (strong . "#ffeeae")
          (polarity . "#ffe994")
          (polarity-strong . "#fffbee")
          (steady . "#997f00")
          (dark-only . "#f5d452")
          (dark-only-emphasis . "#fff0b8")
          (fixed-dark . "#6d5b00")
          (changed-indicator . "#cead00")
          (fine-a . "#695700")
          (fine-ancestor . "#9d8300")
          (fine-b . "#ad9100")
          (fine-c . "#c2a200")
          (current-a . "#483b00")
          (current-ancestor . "#473a00")
          (current-b . "#5c4c00")
          (current-c . "#9c8200")
          (search-group-1-background . "#c8a800")
          (search-group-1-foreground . "#584900")
          (search-group-2-background . "#a18600")
          (search-group-2-foreground . "#584900")
          (indicator-removed . "#6e5b00")
          (indicator-added . "#9c8200")
          (whitespace-big-foreground . "#746100")
          (selected-link . "#fff0b6")))
        (orange .
         ((muted . "#4c3220")
          (selection . "#643500")
          (standalone-selection . "#9d580c")
          (refinement . "#ab5e01")
          (alert . "#c46d01")
          (ansi-low . "#7f4400")
          (ansi-low-bright . "#8a4b00")
          (ansi-mid . "#ab5e01")
          (ansi-mid-bright . "#c06a00")
          (ansi-upper . "#ef8602")
          (ansi-upper-bright . "#ff9c3f")
          (ansi-high . "#ffba81")
          (ansi-vivid . "#ffd9bc")
          (base . "#f2a65a")
          (emphasis . "#ffc27d")
          (vivid . "#ffeada")
          (status-error . "#ffd5b4")
          (status-warning . "#ff9d42")
          (status-success . "#ffe4d0")
          (strong . "#ffeadb")
          (polarity . "#ffe4d0")
          (polarity-strong . "#fffbf7")
          (steady . "#c16c00")
          (dark-only . "#ffcca4")
          (dark-only-emphasis . "#ffeddf")
          (fixed-dark . "#8c4c00")
          (changed-indicator . "#fb9735")
          (fine-a . "#864900")
          (fine-ancestor . "#c76f00")
          (fine-b . "#db7b00")
          (fine-c . "#f58a00")
          (current-a . "#5d3100")
          (current-ancestor . "#5c3000")
          (current-b . "#763f00")
          (current-c . "#c66e00")
          (search-group-1-background . "#fa9019")
          (search-group-1-foreground . "#713d00")
          (search-group-2-background . "#cc7100")
          (search-group-2-foreground . "#713d00")
          (indicator-removed . "#804500")
          (indicator-added . "#b76600")
          (whitespace-big-foreground . "#914f00")
          (selected-link . "#ffe7d5")))
        (red .
         ((muted . "#4a272c")
          (selection . "#800613")
          (standalone-selection . "#a64c47")
          (refinement . "#c8393a")
          (alert . "#ee343b")
          (ansi-low . "#a20118")
          (ansi-low-bright . "#b1001b")
          (ansi-mid . "#d81327")
          (ansi-mid-bright . "#ea3037")
          (ansi-upper . "#ff726b")
          (ansi-upper-bright . "#ff958e")
          (ansi-high . "#ffb5ae")
          (ansi-vivid . "#ffd6d2")
          (base . "#f07178")
          (emphasis . "#ff9a9f")
          (vivid . "#ffe9e6")
          (status-error . "#ffd3ce")
          (status-warning . "#ff9890")
          (status-success . "#ffe3e0")
          (strong . "#ffe9e7")
          (polarity . "#ffe3e0")
          (polarity-strong . "#fffafa")
          (steady . "#d25c57")
          (dark-only . "#ffcac4")
          (dark-only-emphasis . "#ffecea")
          (fixed-dark . "#b22127")
          (changed-indicator . "#ff9088")
          (fine-a . "#ad1a23")
          (fine-ancestor . "#db5d58")
          (fine-b . "#f5635e")
          (fine-c . "#ff7e76")
          (current-a . "#7a0f15")
          (current-ancestor . "#711b1c")
          (current-b . "#8f2727")
          (current-c . "#da5b56")
          (search-group-1-background . "#ff877f")
          (search-group-1-foreground . "#8b2324")
          (search-group-2-background . "#e35c57")
          (search-group-2-foreground . "#8b2324")
          (indicator-removed . "#981b20")
          (indicator-added . "#c64946")
          (whitespace-big-foreground . "#a53332")
          (selected-link . "#ffddd9")))
        (magenta .
         ((muted . "#462b43")
          (selection . "#6b1667")
          (standalone-selection . "#92508c")
          (refinement . "#ac43a5")
          (alert . "#ca44c3")
          (ansi-low . "#8c0888")
          (ansi-low-bright . "#961a91")
          (ansi-mid . "#b62eb0")
          (ansi-mid-bright . "#c740c0")
          (ansi-upper . "#ed66e5")
          (ansi-upper-bright . "#ff7ef6")
          (ansi-high . "#ffa7f7")
          (ansi-vivid . "#ffd0fa")
          (base . "#d98ccf")
          (emphasis . "#efb0e6")
          (vivid . "#ffe5fc")
          (status-error . "#ffcef9")
          (status-warning . "#fb8df2")
          (status-success . "#ffe0fb")
          (strong . "#ffe7fc")
          (polarity . "#ffe0fb")
          (polarity-strong . "#fffafe")
          (steady . "#b862b1")
          (dark-only . "#ffc4f9")
          (dark-only-emphasis . "#ffeafc")
          (fixed-dark . "#972f92")
          (changed-indicator . "#ee8de6")
          (fine-a . "#932a8e")
          (fine-ancestor . "#c063b9")
          (fine-b . "#d66bce")
          (fine-c . "#e97de1")
          (current-a . "#671a63")
          (current-ancestor . "#60215d")
          (current-b . "#7a2e76")
          (current-c . "#be62b8")
          (search-group-1-background . "#ec85e4")
          (search-group-1-foreground . "#772a72")
          (search-group-2-background . "#c663bf")
          (search-group-2-foreground . "#772a72")
          (indicator-removed . "#842a7f")
          (indicator-added . "#af53a9")
          (whitespace-big-foreground . "#8d3988")
          (selected-link . "#ffd7fa")))
        (purple .
         ((muted . "#352c50")
          (selection . "#4b2888")
          (standalone-selection . "#725ca9")
          (refinement . "#7f57d1")
          (alert . "#945ff9")
          (ansi-low . "#622cb5")
          (ansi-low-bright . "#6a37bf")
          (ansi-mid . "#824ae4")
          (ansi-mid-bright . "#915bf6")
          (ansi-upper . "#ad8dff")
          (ansi-upper-bright . "#bda7ff")
          (ansi-high . "#cec0ff")
          (ansi-vivid . "#e3dcff")
          (base . "#b69bf1")
          (emphasis . "#d1b9ff")
          (vivid . "#efebff")
          (status-error . "#e0d8ff")
          (status-warning . "#bea7ff")
          (status-success . "#ebe6ff")
          (strong . "#efecff")
          (polarity . "#ebe6ff")
          (polarity-strong . "#fcfbff")
          (steady . "#8d70d5")
          (dark-only . "#dad0ff")
          (dark-only-emphasis . "#f1eeff")
          (fixed-dark . "#6c42bb")
          (changed-indicator . "#b9a1ff")
          (fine-a . "#693eb6")
          (fine-ancestor . "#9272df")
          (fine-b . "#a27dfa")
          (fine-c . "#b193ff")
          (current-a . "#482981")
          (current-ancestor . "#452c75")
          (current-b . "#593c94")
          (current-c . "#9171de")
          (search-group-1-background . "#b59aff")
          (search-group-1-foreground . "#553891")
          (search-group-2-background . "#9673e8")
          (search-group-2-foreground . "#553891")
          (indicator-removed . "#5c38a0")
          (indicator-added . "#8160cb")
          (whitespace-big-foreground . "#694aab")
          (selected-link . "#e8e2ff")))))))
    (light .
     ((true-color .
       ((neutral .
         ((bg-main . "#f7f8fa")
          (bg-subtle . "#eef0f4")
          (bg-highlight . "#e2e6ed")
          (bg-selection . "#d4dbea")
          (bg-mode-line . "#c6ccd6")
          (bg-panel . "#e2e6ed")
          (bg-ui . "#d9dde5")
          (bg-ui-inactive . "#c6ccd6")
          (bg-fixed-dark . "#111318")
          (fg-main . "#20242c")
          (fg-secondary . "#3f4653")
          (fg-dim . "#515b6c")
          (fg-muted . "#667080")
          (fg-faint . "#808897")
          (fg-on-bright . "#20242c")
          (fg-fixed-light . "#ffffff")
          (fg-fixed-light-gray . "#d3d3d3")
          (fg-fixed-gray . "#d3d3d3")
          (fg-fill-column . "#808080")
          (border . "#8b95a5")
          (border-subtle . "#c6ccd6")
          (border-leading . "#c6ccd6")
          (border-trailing . "#667080")
          (window-divider . "#999999")
          (scrollbar . "#505050")))
        (blue .
         ((muted . "#dce6fb")
          (selection . "#c7dcff")
          (standalone-selection . "#ebf2ff")
          (refinement . "#b7d2ff")
          (alert . "#317fff")
          (ansi-low . "#004cb8")
          (ansi-low-bright . "#0053c9")
          (ansi-mid . "#0d69f2")
          (ansi-mid-bright . "#2a7bff")
          (ansi-upper . "#6da4ff")
          (ansi-upper-bright . "#8db8ff")
          (ansi-high . "#adccff")
          (ansi-vivid . "#d1e2ff")
          (base . "#315fbd")
          (emphasis . "#17499e")
          (vivid . "#195cc7")
          (status-error . "#3577e5")
          (status-warning . "#6ea5ff")
          (status-success . "#2e70de")
          (strong . "#001f56")
          (polarity . "#4b8efe")
          (polarity-strong . "#1750ad")
          (steady . "#3d73cc")
          (dark-only . "#20242c")
          (dark-only-emphasis . "#20242c")
          (fixed-dark . "#1256c1")
          (changed-indicator . "#669fff")
          (fine-a . "#afceff")
          (fine-ancestor . "#83b2ff")
          (fine-b . "#e0ecff")
          (fine-c . "#f3f8ff")
          (current-a . "#d7e6ff")
          (current-ancestor . "#c9deff")
          (current-b . "#f1f6ff")
          (current-c . "#f7faff")
          (search-group-1-background . "#4887ef")
          (search-group-1-foreground . "#c7ddff")
          (search-group-2-background . "#1654b8")
          (search-group-2-foreground . "#c7ddff")
          (indicator-removed . "#134da9")
          (indicator-added . "#4983e5")
          (whitespace-big-foreground . "#295eb5")
          (selected-link . "#2567d3")))
        (cyan .
         ((muted . "#d5eef1")
          (selection . "#68f3fa")
          (standalone-selection . "#ccfdff")
          (refinement . "#5ce9f0")
          (alert . "#03999f")
          (ansi-low . "#006266")
          (ansi-low-bright . "#006b70")
          (ansi-mid . "#01858a")
          (ansi-mid-bright . "#01959c")
          (ansi-upper . "#04bbc3")
          (ansi-upper-bright . "#01d0d9")
          (ansi-high . "#04e6ef")
          (ansi-vivid . "#79f8ff")
          (base . "#006b78")
          (emphasis . "#00515c")
          (vivid . "#007176")
          (status-error . "#008989")
          (status-warning . "#00b7b7")
          (status-success . "#008282")
          (strong . "#002828")
          (polarity . "#00a1a1")
          (polarity-strong . "#005f5f")
          (steady . "#008282")
          (dark-only . "#20242c")
          (dark-only-emphasis . "#20242c")
          (fixed-dark . "#006767")
          (changed-indicator . "#00b2b2")
          (fine-a . "#00e3e3")
          (fine-ancestor . "#00c5c5")
          (fine-b . "#7cffff")
          (fine-c . "#d9fffe")
          (current-a . "#48fcfc")
          (current-ancestor . "#65f0f0")
          (current-b . "#d0fffe")
          (current-c . "#e7fffe")
          (search-group-1-background . "#009899")
          (search-group-1-foreground . "#38f2f2")
          (search-group-2-background . "#006464")
          (search-group-2-foreground . "#38f2f2")
          (indicator-removed . "#005d5e")
          (indicator-added . "#009797")
          (whitespace-big-foreground . "#007272")
          (selected-link . "#007e7e")))
        (green .
         ((muted . "#dcecdf")
          (selection . "#a8f0a9")
          (standalone-selection . "#d6ffd6")
          (refinement . "#9ee6a0")
          (alert . "#00a22b")
          (ansi-low . "#006818")
          (ansi-low-bright . "#01721c")
          (ansi-mid . "#008d24")
          (ansi-mid-bright . "#019f2a")
          (ansi-upper . "#19c63c")
          (ansi-upper-bright . "#3cda52")
          (ansi-high . "#56ee66")
          (ansi-vivid . "#92ff98")
          (base . "#28663a")
          (emphasis . "#174f29")
          (vivid . "#01791e")
          (status-error . "#008f25")
          (status-warning . "#45bb51")
          (status-success . "#008722")
          (strong . "#002a05")
          (polarity . "#2ba63c")
          (polarity-strong . "#006317")
          (steady . "#258531")
          (dark-only . "#20242c")
          (dark-only-emphasis . "#20242c")
          (fixed-dark . "#006c19")
          (changed-indicator . "#50b458")
          (fine-a . "#71e479")
          (fine-ancestor . "#62c569")
          (fine-b . "#a9ffac")
          (fine-c . "#e3ffe3")
          (current-a . "#a3f9a6")
          (current-ancestor . "#a5eea7")
          (current-b . "#ddffdd")
          (current-c . "#edffed")
          (search-group-1-background . "#2c9d3a")
          (search-group-1-foreground . "#99ef9c")
          (search-group-2-background . "#006818")
          (search-group-2-foreground . "#99ef9c")
          (indicator-removed . "#006116")
          (indicator-added . "#339a3e")
          (whitespace-big-foreground . "#107823")
          (selected-link . "#008522")))
        (yellow .
         ((muted . "#f1e8c5")
          (selection . "#f3da7a")
          (standalone-selection . "#fff2c2")
          (refinement . "#ead070")
          (alert . "#9e8401")
          (ansi-low . "#655401")
          (ansi-low-bright . "#6f5c00")
          (ansi-mid . "#8a7302")
          (ansi-mid-bright . "#9b8101")
          (ansi-upper . "#c2a202")
          (ansi-upper-bright . "#d8b501")
          (ansi-high . "#eec804")
          (ansi-vivid . "#ffe068")
          (base . "#755900")
          (emphasis . "#5b4500")
          (vivid . "#766200")
          (status-error . "#917900")
          (status-warning . "#c2a200")
          (status-success . "#897300")
          (strong . "#2b2200")
          (polarity . "#aa8e00")
          (polarity-strong . "#655300")
          (steady . "#897300")
          (dark-only . "#20242c")
          (dark-only-emphasis . "#20242c")
          (fixed-dark . "#6d5b00")
          (changed-indicator . "#bc9d00")
          (fine-a . "#f0c900")
          (fine-ancestor . "#d0ae00")
          (fine-b . "#ffeb9e")
          (fine-c . "#fff8dc")
          (current-a . "#ffe47d")
          (current-ancestor . "#f5db7b")
          (current-b . "#fff6d5")
          (current-c . "#fffae8")
          (search-group-1-background . "#a18700")
          (search-group-1-foreground . "#f8da64")
          (search-group-2-background . "#6a5800")
          (search-group-2-foreground . "#f8da64")
          (indicator-removed . "#625100")
          (indicator-added . "#9f8400")
          (whitespace-big-foreground . "#746100")
          (selected-link . "#816b00")))
        (orange .
         ((muted . "#f5e1d0")
          (selection . "#ffd0ac")
          (standalone-selection . "#ffeee2")
          (refinement . "#ffc392")
          (alert . "#c46d01")
          (ansi-low . "#7f4400")
          (ansi-low-bright . "#8a4b00")
          (ansi-mid . "#ab5e01")
          (ansi-mid-bright . "#c06a00")
          (ansi-upper . "#ef8602")
          (ansi-upper-bright . "#ff9c3f")
          (ansi-high . "#ffba81")
          (ansi-vivid . "#ffd9bc")
          (base . "#8d4700")
          (emphasis . "#713700")
          (vivid . "#925001")
          (status-error . "#b86600")
          (status-warning . "#f58a00")
          (status-success . "#af6000")
          (strong . "#391b00")
          (polarity . "#d77800")
          (polarity-strong . "#814600")
          (steady . "#af6000")
          (dark-only . "#20242c")
          (dark-only-emphasis . "#20242c")
          (fixed-dark . "#8c4c00")
          (changed-indicator . "#ea871d")
          (fine-a . "#ffbf8b")
          (fine-ancestor . "#fd9837")
          (fine-b . "#ffe7d4")
          (fine-c . "#fff6ef")
          (current-a . "#ffdfc6")
          (current-ancestor . "#ffd4b3")
          (current-b . "#fff4ec")
          (current-c . "#fff9f5")
          (search-group-1-background . "#cc7200")
          (search-group-1-foreground . "#ffd3b0")
          (search-group-2-background . "#874a00")
          (search-group-2-foreground . "#ffd3b0")
          (indicator-removed . "#7b4200")
          (indicator-added . "#c66e00")
          (whitespace-big-foreground . "#914f00")
          (selected-link . "#a05800")))
        (red .
         ((muted . "#f3dadd")
          (selection . "#ffcdc8")
          (standalone-selection . "#ffedeb")
          (refinement . "#ffbfb8")
          (alert . "#ee343b")
          (ansi-low . "#a20118")
          (ansi-low-bright . "#b1001b")
          (ansi-mid . "#d81327")
          (ansi-mid-bright . "#ea3037")
          (ansi-upper . "#ff726b")
          (ansi-upper-bright . "#ff958e")
          (ansi-high . "#ffb5ae")
          (ansi-vivid . "#ffd6d2")
          (base . "#a9323d")
          (emphasis . "#88222e")
          (vivid . "#b32228")
          (status-error . "#d84947")
          (status-warning . "#ff7e76")
          (status-success . "#d04140")
          (strong . "#4e0006")
          (polarity . "#f1605b")
          (polarity-strong . "#a02427")
          (steady . "#c24e4a")
          (dark-only . "#20242c")
          (dark-only-emphasis . "#20242c")
          (fixed-dark . "#b22127")
          (changed-indicator . "#fa7871")
          (fine-a . "#ffbcb5")
          (fine-ancestor . "#ff928a")
          (fine-b . "#ffe5e3")
          (fine-c . "#fff6f4")
          (current-a . "#ffddda")
          (current-ancestor . "#ffd2cd")
          (current-b . "#fff4f2")
          (current-c . "#fff9f8")
          (search-group-1-background . "#e45c57")
          (search-group-1-foreground . "#ffd0cc")
          (search-group-2-background . "#aa2428")
          (search-group-2-foreground . "#ffd0cc")
          (indicator-removed . "#981b20")
          (indicator-added . "#d65853")
          (whitespace-big-foreground . "#a53332")
          (selected-link . "#be2f32")))
        (magenta .
         ((muted . "#eedbec")
          (selection . "#ffc5f9")
          (standalone-selection . "#ffebfc")
          (refinement . "#feb4f7")
          (alert . "#ca44c3")
          (ansi-low . "#8c0888")
          (ansi-low-bright . "#961a91")
          (ansi-mid . "#b62eb0")
          (ansi-mid-bright . "#c740c0")
          (ansi-upper . "#ed66e5")
          (ansi-upper-bright . "#ff7ef6")
          (ansi-high . "#ffa7f7")
          (ansi-vivid . "#ffd0fa")
          (base . "#92377f")
          (emphasis . "#742665")
          (vivid . "#982f93")
          (status-error . "#ba51b4")
          (status-warning . "#e97de1")
          (status-success . "#b34aad")
          (strong . "#450042")
          (polarity . "#d268cb")
          (polarity-strong . "#892f84")
          (steady . "#a954a3")
          (dark-only . "#20242c")
          (dark-only-emphasis . "#20242c")
          (fixed-dark . "#972f92")
          (changed-indicator . "#dd7dd5")
          (fine-a . "#ffb3f8")
          (fine-ancestor . "#ef8fe7")
          (fine-b . "#ffe3fb")
          (fine-c . "#fff5fe")
          (current-a . "#ffdafa")
          (current-ancestor . "#ffcdf9")
          (current-b . "#fff2fd")
          (current-c . "#fff8fe")
          (search-group-1-background . "#c763c0")
          (search-group-1-foreground . "#ffcbf9")
          (search-group-2-background . "#91308c")
          (search-group-2-foreground . "#ffcbf9")
          (indicator-removed . "#81277d")
          (indicator-added . "#bb5fb5")
          (whitespace-big-foreground . "#8d3988")
          (selected-link . "#a23a9c")))
        (purple .
         ((muted . "#e6def6")
          (selection . "#ddd4ff")
          (standalone-selection . "#f2efff")
          (refinement . "#d4c8ff")
          (alert . "#945ff9")
          (ansi-low . "#622cb5")
          (ansi-low-bright . "#6a37bf")
          (ansi-mid . "#824ae4")
          (ansi-mid-bright . "#915bf6")
          (ansi-upper . "#ad8dff")
          (ansi-upper-bright . "#bda7ff")
          (ansi-high . "#cec0ff")
          (ansi-vivid . "#e3dcff")
          (base . "#6544a8")
          (emphasis . "#4e3188")
          (vivid . "#6e44bc")
          (status-error . "#8a63de")
          (status-warning . "#b193ff")
          (status-success . "#845cd7")
          (strong . "#310068")
          (polarity . "#9f7af7")
          (polarity-strong . "#623fa7")
          (steady . "#8062c6")
          (dark-only . "#20242c")
          (dark-only-emphasis . "#20242c")
          (fixed-dark . "#6c42bb")
          (changed-indicator . "#ac8dfd")
          (fine-a . "#d1c4ff")
          (fine-ancestor . "#baa3ff")
          (fine-b . "#ede8ff")
          (fine-c . "#f8f7ff")
          (current-a . "#e7e1ff")
          (current-ancestor . "#e0d7ff")
          (current-b . "#f7f5ff")
          (current-c . "#fbf9ff")
          (search-group-1-background . "#9774e8")
          (search-group-1-foreground . "#dfd6ff")
          (search-group-2-background . "#6842b2")
          (search-group-2-foreground . "#dfd6ff")
          (indicator-removed . "#5d39a1")
          (indicator-added . "#8f6fdc")
          (whitespace-big-foreground . "#694aab")
          (selected-link . "#774ec7"))))))))
  "Finite palettes indexed by variant and display class.")

(defun chroma-palette-get (&optional variant display-class)
  "Return palette data for VARIANT and DISPLAY-CLASS.

VARIANT defaults to `dark', and DISPLAY-CLASS defaults to
`true-color'.  Signal `user-error' when the requested palette does not
exist.  The returned value is constant data and must not be modified."
  (let* ((selected-variant (or variant 'dark))
         (selected-class (or display-class 'true-color))
         (variant-data (alist-get selected-variant chroma-palettes))
         (palette (and variant-data
                       (alist-get selected-class variant-data))))
    (unless variant-data
      (user-error "Chroma has no %S variant" selected-variant))
    (unless palette
      (user-error "Chroma has no %S display palette for %S"
                  selected-class selected-variant))
    palette))

(defun chroma-palette-color (hue token &optional variant display-class)
  "Return the color for HUE and TOKEN.

Look up HUE and TOKEN in the finite palette selected by VARIANT and
DISPLAY-CLASS.  Signal `user-error' for an unknown hue or token."
  (let* ((palette (chroma-palette-get variant display-class))
         (hue-data (alist-get hue palette))
         (color (and hue-data (alist-get token hue-data))))
    (unless hue-data
      (user-error "Chroma palette has no %S hue" hue))
    (unless color
      (user-error "Chroma %S palette has no %S token" hue token))
    color))

(provide 'chroma-palette)

;;; chroma-palette.el ends here
